Create build.yml
svsticky/radio pull request #112
Opened 2024-01-22 18:54 UTC by stickyPiston

2024-01-22 22:54 UTC, stickyPiston commented
This is a very rudimentary workflow that runs the linter, builds the application and saves the dist folder as an artefact. Before merging I still want to check whether there are some specifications sad-server requires for the artefact so that it can conveniently use it.

2024-03-22 14:31 UTC, SilasPeters requested changes
Great addition! Few nitpicks here. Also, could you merge main into this PR first?

2024-03-22 14:31 UTC, SilasPeters commented on index.html
> -  <script src="snow.js"></script>
Y no snow? :(

2024-03-22 14:31 UTC, SilasPeters commented on src/components/Activity.jsx
> +
Could you add a comment on why this is needed?

2024-03-22 14:32 UTC, SilasPeters commented
> Before merging I still want to check whether there are some specifications sad-server requires for the artefact so that it can conveniently use it.

Any updates on this?

2024-04-26 10:53 UTC, SilasPeters commented
@stickyPiston just reminding you that this PR has been reviewed

2024-05-09 13:10 UTC, SilasPeters commented
This might close #64

2024-05-12 17:32 UTC, SilasPeters requested changes
Merge master, and I would approve this!

2024-10-09 19:14 UTC, closed without merging